### PR TITLE
Add travis releasing config

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@vogdb please review

**Comment by vogdb** [comment]
for what purpose do we need two node versions in travis?
```
node_js:
- '6'
- '5'
```

**Comment by zazabe** [comment]
I have it on my mac... :) 
```
$ node -v
v6.3.0
```

**Comment by vogdb** [comment]
but you don't run travis on your mac ;)

**Comment by vogdb** [comment]
still lgtm. merge if you want.

**Comment by zazabe** [comment]
I guess it's not so bad to support node 6! let's merge it like that ;)

**Pull request merged**
