### PR TITLE
Use modification time vs file content to generate checksum

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@fauvel please review

**Comment by fauvel** [comment]
What is that?

**Comment by fauvel** [comment]
In `checksum.js`, you should rather put all mtimes into an array, sort it, concatenate it, and take the md5 in hex notation to achieve what you want to. But I'm not fond of it - using the md5 of the contents is way safer and it should be quick enough (the md5 algorithm is designed for speed).

**Comment by zazabe** [comment]
I'll benchmark it again, file content vs mtime ;)

**Comment by zazabe** [comment]
Finally, using file content is very similar in term of perf, so let's use content instead!

> I think now it's broken, only taking the mtime of the last file in the glob to compute a md5 hash

Actually, `crypto.Hash` behaves as a stream > _"This can be called many times with new data as it is streamed."_. see https://nodejs.org/api/crypto.html#crypto_hash_update_data_input_encoding.

**Comment by fauvel** [comment]
Ah ok. This remains a problem, though. If the files pushed to your hashing mechanism are being reordered, for instance, the content hash will change, leading to a recompilation. But that's not what you want to achieve actually – file ordering shouldn't be relevant here imo. What do you think?

**Comment by zazabe** [comment]
Files are always retrieved in the same order, thanks to https://github.com/cargomedia/cm-bundler/blob/master/lib/stream/source/vinyl.js, see https://github.com/cargomedia/cm-bundler/pull/1

**Comment by fauvel** [comment]
lgtm then!

**Pull request merged**
