### PR TITLE
Improve raw content support

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
@fauvel please review

**Comment by zazabe** [comment]
Note: this `prepare` step (8c63909) used to change `browserify` config is not required anymore... wondering if it should be removed or not...

**Comment by zazabe** [comment]
@fauvel ping

**Comment by zazabe** [comment]
@fauvel 👋

**Comment by fauvel** [comment]
Sorry, lots of changes and I'm new to this topic. Lgtm!

**Pull request merged**
